// This file was autogenerated using @guardian/cdk-cli

import "@aws-cdk/assert/jest";
import { SynthUtils } from "@aws-cdk/assert";
import { App } from "@aws-cdk/core";
import { Prism } from "./prism";

describe("The Prism stack", () => {
  it("matches the snapshot", () => {
    const app = new App();
    const stack = new Prism(app, "prism", { app: "deploy" });
    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
  });
});
