# See the documentation for all configuration options https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    schedule:
      # The CDK project does not run in a PROD environment, only CI, so we can afford to use old versions of libraries for a short time. Run Dependabot once a month to reduce the frequency of PRs.
      interval: 'monthly'
    commit-message:
      prefix: "chore(deps): "
    directory: '/cdk'
    # The version of @aws-cdk/* libraries must match those from @guardian/cdk.
    # We'd never be able to update them here independently, so just ignore them.
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "@aws-cdk/*"
