#!/usr/bin/env bash

set -e

# build CDK first to ensure it is on disk for SBT to pick up
(
  cd cdk
  ./script/ci
)

sbt clean scalafmtSbtCheck scalafmtCheckAll compile test debian:packageBin

# `sbt debian:packageBin` produces `target/prism_1.0-SNAPSHOT_all.deb`. Rename it to something easier.
mv target/prism_1.0-SNAPSHOT_all.deb target/prism.deb
