#!/usr/bin/env bash

set -e

# build CDK first to ensure it is on disk for SBT to pick up
(
  cd cdk
  npm ci
  npm run lint
  npm test
  npm run synth
)

sbt clean scalafmtSbtCheck scalafmtCheckAll compile test debian:packageBin

mkdir -p dist
mv target/prism_1.0-SNAPSHOT_all.deb "dist/prism-$GITHUB_RUN_NUMBER.deb"
